### ISSUE TITLE
Upgrade 1.10.0 installation error - QGis / libQt5Core.so.5

### ISSUE THREAD

**Issue by index-git** [LayerManager/layman#335]
using `make start-demo` may produce following error:
```
/usr/lib/cgi-bin/qgis_mapserv.fcgi: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
```

**Comment by index-git** [comment]
According to our investigation, this error is related to the kernel version of the host server. It seems, that at least 4.11 is needed for QGis server installation.

**Comment by jirik** [comment]
See also https://github.com/gem/oq-qgis-server/tree/9345efc73d16f38426b33c65f72bf368618355ad#requisites

**Comment by jirik** [comment]
Solution is to upgrade linux kernel, see requirements in README.
