### ISSUE TITLE
 mod_wsgi (pid=30997): Exception occurred processing WSGI script

### ISSUE THREAD

**Issue by mq27** [LayerManager/layman#372]
flaskapp wsgi script is showing exception error after few months. Python script is using flaskapp and its WSGI script. the python script contains two functions when 1st function is called the script shows output fine but when 2nd function is caleed script throws error  mod_wsgi (pid=30997): Exception occurred processing WSGI script '/var/www/FlaskApp/flaskapp.wsgi'.
[Wed May 19 05:19:52.128620 2021] [wsgi:error] [pid 30997:tid 140373473056512] [client 111.68.110.251:2171] Traceback (most recent call last):
[Wed May 19 05:19:52.128713 2021] [wsgi:error] [pid 30997:tid 140373473056512] [client 111.68.110.251:2171]   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2464, in __call__
[Wed May 19 05:19:52.128721 2021] [wsgi:error] [pid 30997:tid 140373473056512] [client 111.68.110.251:2171]     return self.wsgi_app(environ, start_response)
[Wed May 19 05:19:52.128731 2021] [wsgi:error] [pid 30997:tid 140373473056512] [client 111.68.110.251:2171]   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2450, in wsgi_app
[Wed May 19 05:19:52.128737 2021] [wsgi:error] [pid 30997:tid 140373473056512] [client 111.68.110.251:2171]     response = self.handle_exception(e)
[Wed May 19 05:19:52.128745 2021] [wsgi:error] [pid 30997:tid 140373473056512] [client 111.68.110.251:2171]   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1867, in handle_exception
[Wed May 19 05:19:52.128751 2021] [wsgi:error] [pid 30997:tid 140373473056512] [client 111.68.110.251:2171]     reraise(exc_type, exc_value, tb)
[Wed May 19 05:19:52.128759 2021] [wsgi:error] [pid 30997:tid 140373473056512] [client 111.68.110.251:2171]   File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
[Wed May 19 05:19:52.128765 2021] [wsgi:error] [pid 30997:tid 140373473056512] [client 111.68.110.251:2171]     raise value
[Wed May 19 05:19:52.128773 2021] [wsgi:error] [pid 30997:tid 140373473056512] [client 111.68.110.251:2171]   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
[Wed May 19 05:19:52.128778 2021] [wsgi:error] [pid 30997:tid 140373473056512] [client 111.68.110.251:2171]     response = self.full_dispatch_request()
[Wed May 19 05:19:52.128787 2021] [wsgi:error] [pid 30997:tid 140373473056512] [client 111.68.110.251:2171]   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
[Wed May 19 05:19:52.128793 2021] [wsgi:error] [pid 30997:tid 140373473056512] [client 111.68.110.251:2171]     rv = self.handle_user_exception(e)
[Wed May 19 05:19:52.128800 2021] [wsgi:error] [pid 30997:tid 140373473056512] [client 111.68.110.251:2171]   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
[Wed May 19 05:19:52.128806 2021] [wsgi:error] [pid 30997:tid 140373473056512] [client 111.68.110.251:2171]     reraise(exc_type, exc_value, tb)
[Wed May 19 05:19:52.128813 2021] [wsgi:error] [pid 30997:tid 140373473056512] [client 111.68.110.251:2171]   File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
[Wed May 19 05:19:52.128819 2021] [wsgi:error] [pid 30997:tid 140373473056512] [client 111.68.110.251:2171]     raise value
[Wed May 19 05:19:52.128827 2021] [wsgi:error] [pid 30997:tid 140373473056512] [client 111.68.110.251:2171]   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
[Wed May 19 05:19:52.128849 2021] [wsgi:error] [pid 30997:tid 140373473056512] [client 111.68.110.251:2171]     rv = self.dispatch_request()
[Wed May 19 05:19:52.128858 2021] [wsgi:error] [pid 30997:tid 140373473056512] [client 111.68.110.251:2171]   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
[Wed May 19 05:19:52.128864 2021] [wsgi:error] [pid 30997:tid 140373473056512] [client 111.68.110.251:2171]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed May 19 05:19:52.128871 2021] [wsgi:error] [pid 30997:tid 140373473056512] [client 111.68.110.251:2171]   File "/var/www/FlaskApp/FlaskApp/__init__.py", line 407, in retrun_face_detected_and_start_recognition
[Wed May 19 05:19:52.128877 2021] [wsgi:error] [pid 30997:tid 140373473056512] [client 111.68.110.251:2171]     loop.run_until_complete(find_face(imgID=imgID, imageFile=file))
[Wed May 19 05:19:52.128884 2021] [wsgi:error] [pid 30997:tid 140373473056512] [client 111.68.110.251:2171]   File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
[Wed May 19 05:19:52.128889 2021] [wsgi:error] [pid 30997:tid 140373473056512] [client 111.68.110.251:2171]     return future.result()
[Wed May 19 05:19:52.128897 2021] [wsgi:error] [pid 30997:tid 140373473056512] [client 111.68.110.251:2171]   File "/var/www/FlaskApp/FlaskApp/__init__.py", line 273, in find_face
[Wed May 19 05:19:52.128902 2021] [wsgi:error] [pid 30997:tid 140373473056512] [client 111.68.110.251:2171]     encoding = await do_the_face_find(imgID=imgID, imageFile=imageFile)
[Wed May 19 05:19:52.128909 2021] [wsgi:error] [pid 30997:tid 140373473056512] [client 111.68.110.251:2171]   File "/var/www/FlaskApp/FlaskApp/__init__.py", line 238, in do_the_face_find
[Wed May 19 05:19:52.128914 2021] [wsgi:error] [pid 30997:tid 140373473056512] [client 111.68.110.251:2171]     imgID=imgID, unknown_encoding=unknown_encoding)
[Wed May 19 05:19:52.128921 2021] [wsgi:error] [pid 30997:tid 140373473056512] [client 111.68.110.251:2171]   File "/var/www/FlaskApp/FlaskApp/__init__.py", line 201, in write_unknown_encoding_to_json
[Wed May 19 05:19:52.128926 2021] [wsgi:error] [pid 30997:tid 140373473056512] [client 111.68.110.251:2171]     compare_faces_and_update_json(imgID=imgID)
[Wed May 19 05:19:52.128933 2021] [wsgi:error] [pid 30997:tid 140373473056512] [client 111.68.110.251:2171]   File "/var/www/FlaskApp/FlaskApp/__init__.py", line 172, in compare_faces_and_update_json
[Wed May 19 05:19:52.128938 2021] [wsgi:error] [pid 30997:tid 140373473056512] [client 111.68.110.251:2171]     unknown_data_entry[NAMES] = [unknown_data_entry[NAMES][-1]]
[Wed May 19 05:19:52.128959 2021] [wsgi:error] [pid 30997:tid 140373473056512] [client 111.68.110.251:2171] IndexError: list index out of range

however boths functions are showing output fine since two months but 2nd function throwing error from last 2 days please help my WSGI script is as follows:

`#!/usr/bin/python
import sys
import logging

import flask
from flask import request, jsonify
import os

from pyfcm import FCMNotification

import numpy as np
import face_recognition
import json

import asyncio
logging.basicConfig(stream=sys.stderr)
sys.path.insert(0,"/var/www/FlaskApp/FlaskApp/__init__.py")

from FlaskApp import app as application
application.secret_key = 'Add your secret key'
`

**Comment by jirik** [comment]
@mq27 It seems your issue is related to flask, not to Layman, so consider posting it in [flask repository](https://github.com/pallets/flask).
