### ISSUE TITLE
Include metadata resource in the capabilities of published services

### ISSUE THREAD

**Issue by fzadrazil** [LayerManager/layman#520]
MetadataURL should be included in the XML capabilities of OGC services. Eg.
https://mapy.geology.cz/arcgis/services/Pudy/pudni_typy50/MapServer/WMSServer?request=GetCapabilities&service=WMS

**Comment by jirik** [comment]
If map composition consists of external WMS layers, we want Layman to do following:
- for each external WMS service, check if metadata record exists in CSW (Micka), and if not, create it
- for each external WMS layer, check if metadata record exists in CSW (Micka), and if not, create it and bind it with WMS service metadata record
- add metadata record of each external WMS layer as coupled resource to matadata record if given map composition

**Comment by jirik** [comment]
Previous comment moved to standalone issue #827

**Comment by jirik** [comment]
Add `MetadataURL` element to each layer now. Do not add `inspire_common:MetadataUrl` element now.
