### ISSUE TITLE
Include WMS/WFS status in GET Layers and GET Workspace Layers responses

### ISSUE THREAD

**Issue by fzadrazil** [LayerManager/layman#528]
Users of Layman clients should be informed whether a layer has been already published, is still in processing or is broken. It would be much more effective if the client can get the status from general requests (GET Layers, GET Workspace Layers) so it doesn't have to check all the existing layers one by one.

**Comment by jirik** [comment]
From discussion: ordering and filtering by publication status is not needed.

**Comment by jirik** [comment]
With current code it's possible to quickly distinguish if layer is still in process, or it is not. On the other hand, it's not possible to quickly and certainly distinguish, if layer is or isn't complete or broken.

**Comment by jirik** [comment]
Redis stores information about result of last async action of each layer/map. We can use such information to estimate publication status in multi-publication endpoints.

However, there are at least three situations when information in Redis can be wrong:
- After Layman restart, redis is flushed and result of last async action is therefore lost
- After [`result_expires`](https://docs.celeryproject.org/en/stable/userguide/configuration.html#std-setting-result_expires) (1 day by default) from async task run, result of async action is deleted
- Removing of GeoServer layer or Micka record by someone else than Layman

**Comment by jirik** [comment]
We try to use existing Redis information first, even it's not always true.

**Comment by jirik** [comment]
In case of INCOMPLETE, it;s important to show to user why it's incomplete (e.g. error message, what's missing).

**Comment by jirik** [comment]
The most important information is status of WMS/WFS.
