### ISSUE TITLE
Loss of data for binary rasters

### ISSUE THREAD

**Issue by fzadrazil** [LayerManager/layman#551]
There is a significant loss of data for small scales when publishing binary rasters as WMS, see the file attached.
[M_Merc.zip](https://github.com/LayerManager/layman/files/7806792/M_Merc.zip)

Sample WMS requests
[Req1 - renders fine](http://157.230.109.174/geoserver/fzadrazil_wms/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=1814838.364313394995,6539071.694071477279,1822968.542632089695,6544316.098373478279&CRS=EPSG:3857&WIDTH=1203&HEIGHT=776&LAYERS=m_merc&STYLES=&FORMAT=image/png&DPI=120&MAP_RESOLUTION=120&FORMAT_OPTIONS=dpi:120&TRANSPARENT=TRUE)
[Req2 - data are heavily reduced](http://157.230.109.174/geoserver/fzadrazil_wms/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=1810404.950367373414,6536381.909390811808,1826665.307004763279,6546870.717994813807&CRS=EPSG:3857&WIDTH=1203&HEIGHT=776&LAYERS=m_merc&STYLES=&FORMAT=image/png&DPI=120&MAP_RESOLUTION=120&FORMAT_OPTIONS=dpi:120&TRANSPARENT=TRUE)

**Comment by fzadrazil** [comment]
Should be solved by supporting new coordinates systems, I guess? I recall the issue was caused by the transformation from native CRS (4326) to EPSG:3857.

**Comment by fzadrazil** [comment]
Updated the sample links to the layer published on the test instance of Layman, the issue persists.

**Comment by jirik** [comment]
Currently, `average` is used in gdaladdo: https://gdal.org/programs/gdaladdo.html#description

Other options:

nearest: 
![image](https://user-images.githubusercontent.com/2271850/155112275-3d573e40-03c2-40e9-b7a4-c778a0b4796f.png)

rms: 
![image](https://user-images.githubusercontent.com/2271850/155112521-90b49735-3c30-4ae8-9fdd-406d94d078ec.png)

bilinear: 
![image](https://user-images.githubusercontent.com/2271850/155112669-95a96e69-8f28-4b96-8f70-0909207f3904.png)

gauss: 
![image](https://user-images.githubusercontent.com/2271850/155112811-cdce2081-a43a-4ddc-996d-98f4a9587ed8.png)

cubic: 
![image](https://user-images.githubusercontent.com/2271850/155113053-da2744c8-1d18-4942-89e2-aeb980ffa384.png)

cubicspline: 
![image](https://user-images.githubusercontent.com/2271850/155113225-e891bc21-8e3e-4924-8927-cd3e6c0c3078.png)

lanczos: 
![image](https://user-images.githubusercontent.com/2271850/155113364-bfe69b3a-1560-479b-a2ad-40e5392f6656.png)

average_magphase: 
![image](https://user-images.githubusercontent.com/2271850/155113576-4d7cce00-bf34-4944-8ae3-70d7ff259f72.png)

mode: 
![image](https://user-images.githubusercontent.com/2271850/155113731-12eb7881-164c-4ecd-99a0-82b96e4e5679.png)

**Comment by fzadrazil** [comment]
Seems that the simplest option gives the best result. The question is whether it will influence other types of rasters where the result could be worse on the contrary. Or even the same raster zoomed in more detail.
