### ISSUE TITLE
Case sensitive data file extensions

### ISSUE THREAD

**Issue by fzadrazil** [LayerManager/layman#599]
File extensions seems to be case sensitive for Layman right now. Eg. it is not allowed to publish kn.SHP, must be kn.shp.

**Comment by index-git** [comment]
Places, where `lower()` is needed:
- src/layman/layer/filesystem/input_file.py::get_file_type 100
- src/layman/layer/filesystem/input_file.py::get_main_file_name 83
- src/layman/layer/filesystem/util.py::raw_main_file_paths 94
- src/layman/layer/filesystem/util.py::raw_or_archived_main_file_paths 99
- src/layman/layer/filesystem/input_file.py::get_file_name_mappings 274
