### ISSUE TITLE
micka.soap.refresh breaks the layer

### ISSUE THREAD

**Issue by fzadrazil** [LayerManager/layman#611]
It happens for some layers that the layman.layer.micka.soap.refresh task lasts forever (or at least for a very long time). The layer is not available the whole time. Could micka.soap.refresh be isolated so the layers won't get stuck?

Eg. https://hub4everybody.lesprojekt.cz/flower/task/5ac6adb3-f40d-44e4-9b50-6a36b7ea8906

**Comment by jirik** [comment]
@fzadrazil Not sure what do you mean by "isolation" and "not available". Currently, map/layer is locked until all asynchronous tasks finish, one of those tasks is micka.soap.refresh. During the lock, Layman refuses all PATCH requests to the layer. On the other hand, during the lock you can ask Layman with GET Layer, and if publication to GeoServer is finished, you can use WMS/WFS too.

If current state is not enough, here are some ideas what we can do
- Make Micka optional dependency, so admin can turn Layman-Micka communication off. No CSW, no metadata records.
- Layer/map enables PATCH requests even if micka.soap.refresh is still running.
- Add timeout to micka.soap.refresh, so if Micka will not respond in e.g. 20 s, micka.soap.refresh fails, layer is INCLOMPLETE, but it's not locked.
- ? (ideas welcome)

First two options require system changes, so they are difficult to implement. Third option should be more easy.

**Comment by fzadrazil** [comment]
> During the lock, Layman refuses all PATCH requests to the layer. On the other hand, during the lock you can ask Layman with GET Layer

That is important for us. But is the client able to recognize this state when publishing is over but some async tasks are still running? We are not even trying to request layers/maps that don't have the COMPLETE status right now since we have expected them to not be ready.

**Comment by index-git** [comment]
Conclusions from call:
- Client will look for `url` subkey in `WMF`/`WFS` keys
- Layman should always answer GET Layer request, so each time it did not it's an error
