### ISSUE TITLE
WMS LegendURL for qgis layers

### ISSUE THREAD

**Issue by index-git** [LayerManager/layman#613]
There is no LegendURL element in GeoServer's WMS response for qgis layers. WMS response on QGIS leads to QGIS legend, which is correct.

Solution proposal:
1) Add Style element with LegendURL subelement to WMS GetCapabilities response with values from QGIS response.
2) Redirect LegendURL query to QGIS legend, as of now, QGIS is not accessible.

**Comment by jirik** [comment]
Implemented by GeoServer upgrade.
