### ISSUE TITLE
Add time support for WMS

### ISSUE THREAD

**Issue by jirik** [LayerManager/layman#635]
https://docs.geoserver.org/stable/en/user/services/wms/time.html

**Comment by jirik** [comment]
Let's solve only raster files first

**Comment by jirik** [comment]
https://geoserver.geo-solutions.it/multidim/multidim/imagemosaic/mosaic_indexer.html
https://docs.geoserver.org/stable/en/user/services/wms/time.html
https://docs.geoserver.org/stable/en/user/data/webadmin/layers.html#data-webadmin-layers-edit-dimensions

**Comment by fzadrazil** [comment]
Sample raster time series
[RGB.ZIP](https://github.com/LayerManager/layman/files/9280639/RGB.ZIP)
