### ISSUE TITLE
Enable to publish QML with labels only

### ISSUE THREAD

**Issue by jirik** [LayerManager/layman#764]
Layman enables to publish
- QML with symbols only
- QML with symbols and labels

but it does not enable to publish
- QML with labels only

**Comment by fzadrazil** [comment]
Sample QGIS project with data and QML file
[anotace.zip](https://github.com/LayerManager/layman/files/10697616/anotace.zip)

**Comment by fzadrazil** [comment]
[kn.zip](https://github.com/LayerManager/layman/files/11211514/kn.zip)

**Comment by jirik** [comment]
Some QMLs extracted and adjusted from original kn.zip.
[kn-qml.zip](https://github.com/LayerManager/layman/files/11477295/kn-qml.zip)
